// Code generated by MockGen. DO NOT EDIT.
// Source: ./create.go

// Package mocks is a generated GoMock package.
package mocks

import (
	tweet "challenge_be/pkg/types/tweet/options"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCreateUseCase is a mock of CreateUseCase interface.
type MockCreateUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateUseCaseMockRecorder
}

// MockCreateUseCaseMockRecorder is the mock recorder for MockCreateUseCase.
type MockCreateUseCaseMockRecorder struct {
	mock *MockCreateUseCase
}

// NewMockCreateUseCase creates a new mock instance.
func NewMockCreateUseCase(ctrl *gomock.Controller) *MockCreateUseCase {
	mock := &MockCreateUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateUseCase) EXPECT() *MockCreateUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateUseCase) Execute(arg0 context.Context, arg1 tweet.InputCreateTweet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateUseCaseMockRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateUseCase)(nil).Execute), arg0, arg1)
}
